# -*- coding: utf-8 -*-
"""matrix_ops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3oHbusdBf39WnqyVx5lmv_QPHkDTE2H
"""

# Matrix Addition
def matrix_add(A, B):
    result = []

    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] + B[i][j])
        result.append(row)

    return result


# Matrix Transpose
def matrix_transpose(matrix):
    return [list(row) for row in zip(*matrix)]


# Matrix Multiplication
def matrix_multiply(A, B):

    if len(A[0]) != len(B):
        return "Matrix multiplication not possible"

    result = [
        [sum(a*b for a, b in zip(row_a, col_b))
        for col_b in zip(*B)]
        for row_a in A
    ]

    return result


# Testing
if __name__ == "__main__":

    a = [[1,2],[3,4]]
    b = [[5,6],[7,8]]

    print(matrix_add(a,b))
    print(matrix_transpose(a))
    print(matrix_multiply(a,b))