# -*- coding: utf-8 -*-
"""student_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3oHbusdBf39WnqyVx5lmv_QPHkDTE2H
"""

import json

# Initial student records (10 students, 3 subjects)
records = [
    ["Aman", "Math", 88],
    ["Priya", "Physics", 91],
    ["Rahul", "Math", 76],
    ["Sneha", "Chemistry", 84],
    ["Rohit", "Physics", 79],
    ["Anita", "Math", 92],
    ["Vikas", "Chemistry", 73],
    ["Pooja", "Physics", 85],
    ["Karan", "Math", 81],
    ["Neha", "Chemistry", 89]
]


# Add Student
def add_student(name, subject, marks):
    global records
    for r in records:
        if r[0] == name and r[1] == subject:
            print("Duplicate record not allowed.")
            return
    records.append([name, subject, marks])
    print("Student added successfully.")


# Get Top 3 Students
def get_toppers(subject):
    subject_students = [r for r in records if r[1] == subject]
    toppers = sorted(subject_students, key=lambda x: x[2], reverse=True)[:3]
    return toppers


# Class Average
def class_average(subject):
    marks = [m[2] for m in records if m[1] == subject]
    if not marks:
        return 0
    return sum(marks) / len(marks)


# Above Average Students
def above_average_students():
    all_marks = [r[2] for r in records]
    avg = sum(all_marks) / len(all_marks)

    return [r for r in records if r[2] > avg]


# Remove Student
def remove_student(name):
    global records
    records = [r for r in records if r[0] != name]
    print("Student records removed.")


# Save to file
def save_records():
    with open("students.txt", "w") as f:
        for r in records:
            f.write(",".join(map(str, r)) + "\n")


# Menu Driven Program
def menu():
    while True:
        print("\nStudent Management System")
        print("1 Add Student")
        print("2 Show Toppers")
        print("3 Show Class Average")
        print("4 Show Above Average Students")
        print("5 Remove Student")
        print("6 Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            name = input("Name: ")
            subject = input("Subject: ")
            marks = int(input("Marks: "))
            add_student(name, subject, marks)

        elif choice == "2":
            subject = input("Enter subject: ")
            print(get_toppers(subject))

        elif choice == "3":
            subject = input("Enter subject: ")
            print("Average:", class_average(subject))

        elif choice == "4":
            print(above_average_students())

        elif choice == "5":
            name = input("Enter student name: ")
            remove_student(name)

        elif choice == "6":
            save_records()
            print("Records saved to students.txt")
            break

        else:
            print("Invalid option")


if __name__ == "__main__":
    menu()